######################################################################
# Automatically generated by qmake (3.1) Sat Apr 15 00:21:28 2017
######################################################################

TEMPLATE = app
TARGET = radx2grid
CONFIG -= qt
CONFIG -= app_bundle

INCLUDEPATH += \
    /usr/local/include

# Input
HEADERS += \
           apps/Radx/src/Radx2Grid/Args.hh \
           apps/Radx/src/Radx2Grid/CartInterp.hh \
           apps/Radx/src/Radx2Grid/GridSet.hh \
           apps/Radx/src/Radx2Grid/Interp.hh \
           apps/Radx/src/Radx2Grid/OutputMdv.hh \
           apps/Radx/src/Radx2Grid/Params.hh \
           apps/Radx/src/Radx2Grid/PolarInterp.hh \
           apps/Radx/src/Radx2Grid/PpiInterp.hh \
#          apps/Radx/src/Radx2Grid/PrevReorderInterp.hh \
           apps/Radx/src/Radx2Grid/Radx2Grid.hh \
           apps/Radx/src/Radx2Grid/Radx2GridPlus.hh \
           apps/Radx/src/Radx2Grid/ReorderInterp.hh \
           apps/Radx/src/Radx2Grid/SatInterp.hh \
           apps/Radx/src/Radx2Grid/SvdData.hh \
           apps/Radx/src/Radx2Grid/Thread.hh \
           apps/Radx/src/Radx2Grid/VolumePointsSet.hh \
           apps/Radx/src/Radx2Grid/VolumeStream.hh \
           apps/Radx/src/Radx2Grid/PolarDataStream.hh \
           apps/Radx/src/Radx2Grid/Polar2Cartesian.hh \
           apps/Radx/src/Radx2Grid/Cartesian2Grid.hh

SOURCES += apps/Radx/src/Radx2Grid/Args.cc \
           apps/Radx/src/Radx2Grid/Cartesian2Grid.cpp \
           apps/Radx/src/Radx2Grid/CartInterp.cc \
           apps/Radx/src/Radx2Grid/GridSet.cc \
           apps/Radx/src/Radx2Grid/Interp.cc \
           apps/Radx/src/Radx2Grid/Main.cc \
           apps/Radx/src/Radx2Grid/OutputMdv.cc \
           apps/Radx/src/Radx2Grid/Params.cc \
           apps/Radx/src/Radx2Grid/Polar2Cartesian.cpp \
           apps/Radx/src/Radx2Grid/PolarDataStream.cpp \
           apps/Radx/src/Radx2Grid/PolarInterp.cc \
           apps/Radx/src/Radx2Grid/PpiInterp.cc \
#           apps/Radx/src/Radx2Grid/PrevReorderInterp.cc \
           apps/Radx/src/Radx2Grid/Radx2Grid.cc \
           apps/Radx/src/Radx2Grid/Radx2GridPlus.cc \
           apps/Radx/src/Radx2Grid/ReorderInterp.cc \
           apps/Radx/src/Radx2Grid/SatInterp.cc \
           apps/Radx/src/Radx2Grid/SvdData.cc \
           apps/Radx/src/Radx2Grid/Thread.cc \
           apps/Radx/src/Radx2Grid/VolumePointsSet.cc \
           apps/Radx/src/Radx2Grid/VolumeStream.cc

OTHER_FILES += apps/Radx/src/Radx2Grid/makefile.am

LIBS += -lradar \
    -lFmq \
    -lSpdb \
    -lMdv \
    -lphysics \
    -lRadx \
    -lrapformats \
    -ldsserver \
    -ldidss \
    -leuclid \
    -lrapmath \
    -ltoolsa \
    -ldataport \
    -ltdrp \
    -lkd \
    -lnetcdf_c++4 \
    -lnetcdf_c++ \
    -lnetcdf \
    -lhdf5_cpp \
    -lhdf5_hl \
    -lhdf5 \
    -ludunits2 \
    -lz \
    -lbz2 \
    -lpthread \
    -lexpat \
    -lm \
    -lfftw3 \
    -ltbb

LIBS += -L/usr/local/lib

macx:{
    #LIBS += -L/opt/intel/compilers_and_libraries/mac/tbb/lib
    #INCLUDEPATH += /opt/intel/compilers_and_libraries/mac/tbb/include
}
