#! /bin/csh
#
# Create the usage and params .txt files for the web page
# =======================================================

foreach app ( \
    Radx2Grid \
    RadxCheck \
    RadxConvert \
    RadxCov2Mom \
    RadxDiff \
    RadxEvad \
    RadxFilter \
    RadxMergeFields \
    RadxPartRain \
    RadxPrint \
    FixCfradialPaths \
    FixRadxPointing \
  )
  $app -h > ${app}_usage.txt
  $app -print_params long > ${app}_params.txt
end

