#! /bin/csh
#
# checkout for radx under configure

# distribution

cvs co distribs/radx

# libraries

cvs co -P libs/_makefiles
/bin/cp libs/_makefiles/makefile.radx libs/makefile

cvs co -P libs/Fmq
cvs co -P libs/Mdv
cvs co -P libs/NcfMdv
cvs co -P libs/Radx
cvs co -P libs/Spdb
cvs co -P libs/dataport
cvs co -P libs/didss
cvs co -P libs/dsserver
cvs co -P libs/dsdata
cvs co -P libs/euclid
cvs co -P libs/physics
cvs co -P libs/radar
cvs co -P libs/rapformats
cvs co -P libs/rapmath
cvs co -P libs/tdrp
cvs co -P libs/toolsa
cvs co -P libs/kd

# perl modules are a special case

cvs co -P libs/perl5/src

# apps

cvs co -P apps/_makefiles
/bin/cp apps/_makefiles/makefile.radx apps/makefile

cvs co -P apps/Radx
/bin/cp apps/Radx/src/_makefiles/makefile.radx apps/Radx/src/makefile

cvs co -P apps/tdrp
/bin/cp apps/tdrp/src/_makefiles/makefile.radx apps/tdrp/src/makefile

# projects

cvs co -P projects/radx

# autoconf / automake

cvs co make_bin
cvs co make_include

