#
# Recursive make for AWC libraries
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	cidd \
        dataport \
        toolsa \
	symprod \
        didss \
        dsserver \
	rapformats \
        euclid \
	mdv \
	titan \
	perl5 \
	physics \
	rapmath \
	rapplot \
	spdbFormats \
	spdb

$(TARGETS): FORCE
	$(MAKE) $(SUB_DIRS) TARGET=$@

$(SUB_DIRS): FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:





