#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
        cidd \
        dataport \
	devguide \
	didss \
	dsserver \
	euclid \
	Fmq \
	Mdv \
	olgx \
	rapformats \
	rapmath \
	rapplot \
	shapelib \
	Spdb \
        tdrp \
        toolsa \
	xview

$(TARGETS): FORCE
	$(MAKE) $(SUB_DIRS) TARGET=$@

$(SUB_DIRS): FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:





