#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	dataport \
	didss \
	dsdata \
	dsserver \
	euclid \
	Fmq \
	grib \
	grib2 \
	grid \
	icing \
	Mdv \
	perl5 \
	python \
	physics \
	Radx \
	rapformats \
	rapmath \
	Spdb \
	tdrp \
	toolsa


$(TARGETS): FORCE
	$(MAKE) $(SUB_DIRS) TARGET=$@

$(SUB_DIRS): FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:





