#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	Fmq \
        Mdv \
	Spdb \
	dataport \
	didss \
	dsdata \
	dsserver \
	euclid \
	grib \
	mdv \
	ocolide \
	perl5 \
	physics \
	rapformats \
	rapmath \
	tdrp \
	tetwws \
	toolsa


$(TARGETS): FORCE
	$(MAKE) $(SUB_DIRS) TARGET=$@

$(SUB_DIRS): FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:





