#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	dataport \
	perl5 \
	tdrp \
	dsserver \
	didss \
	toolsa \
	rapmath \
	aos_jaws \
	JawsAlg \
	JawsAlgGL \
	Wp \
	Tetwws \
	TetwwsGL \
	TetwwsNC \
	tetwws_srdm \
	ctetwws \
	wp

$(TARGETS): FORCE
	$(MAKE) $(SUB_DIRS) TARGET=$@

$(SUB_DIRS): FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:


