#
# Recursive make for TITAN libraries
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	dataport \
	didss \
	dsdata \
	dsserver \
	euclid \
	Fmq \
	grib2 \
	mdv \
	Mdv \
	perl5 \
	physics \
	python \
	rapformats \
	rapmath \
	Spdb \
	tdrp \
	titan \
	toolsa

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets
