#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	dataport \
	toolsa \
	didss \
	dsserver \
	euclid \
	mel_bufr \
	rapmath \
	rapformats \
	physics \
	tdrp \
	Spdb \
	InsituTurb \
	perl5 \
	python \
	mdv \
	Mdv


$(TARGETS): FORCE
	$(MAKE) $(SUB_DIRS) TARGET=$@

$(SUB_DIRS): FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:

