#
# Recursive make for HWT libraries
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
        dataport \
	devguide \
        didss \
	dsdata \
	dsserver \
        euclid \
	Fmq \
	grib \
	grib2 \
	Mdv \
	olgx \
	perl5 \
	physics \
	python \
	rapformats \
	rapmath \
	rapplot \
	shapelib \
	Spdb \
	tdrp \
        toolsa \
	xview


include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets






