#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

SUB_DIRS = \
	dataport \
	perl5 \
	tdrp \
	dsserver \
	didss \
	toolsa \
	rapmath

include $(RAP_MAKE_INC_DIR)/rap_make_recursive_dir_targets


