#
# Recursive make - makes the subdirectory code
#

include $(RAP_MAKE_INC_DIR)/rap_make_macros

TARGETS = $(GENERAL_TARGETS) $(LIB_TARGETS) $(DOC_TARGETS) $(INSTALL_TARGETS)

#	grib \
#	grid \
#	perl5 \
#	symprod \
#	python \
#	tdrp
SUB_DIRS = \
	dataport \
	didss \
	dsdata \
	dsserver \
	euclid \
	Fmq \
	grib2 \
	Mdv \
	physics \
	rapformats \
	rapmath \
	Spdb \
	toolsa


$(TARGETS): FORCE
	$(MAKE) $(SUB_DIRS) TARGET=$@

$(SUB_DIRS): FORCE
	cd $@; $(MAKE) $(TARGET)

FORCE:





